apiVersion: app/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    containers:
    - name: python
      image: python
      ports:
      - containerPort: 8080
      env:
      - name: POSTGRES_USER
        value:
      - name: POSTGRES_PASSWORD
        value:
      - name: POSTGRES_URL
        value: