apiVersion: autoscaling/v2
kind: VerticalPodAutoScaler
metadata:
  name: nginx-vpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
    namespace: nginx-vpa
  updatePolicy:
    updateMode: Recreate
  resourcePolicy:
    containerPolicy:
    - containerName: "nginx"
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2
        memory: 2Gi
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits
