apiVersion: autoscaling/v2
kind: HorizontalPodAutoScaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: nginx
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resources
      resource:
        name: cpu
        target:
          type:  Utilization
          averageUtilization: 50